services:
  wimpeytrack-api:
    image: ghcr.io/fl3my/wimpeytrack-api:latest
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - AzureDocumentIntelligence__EndPoint=${AZURE_DOCUMENT_ENDPOINT}
      - AzureDocumentIntelligence__ApiKey=${AZURE_DOCUMENT_APIKEY}
      - Gmail__ClientId=${GMAIL_CLIENT_ID}
      - Gmail__ClientSecret=${GMAIL_CLIENT_SECRET}
      - Gmail__ClientEmail=${GMAIL_CLIENT_EMAIL}
    restart: unless-stopped
    volumes:
      - wimpeytrack-db:/app/data
      - wimpeytrack-uploads:/app/wwwroot/uploads
      - wimpeytrack-reports:/app/wwwroot/reports
    networks:
      - proxy
  
  document-vision-service:
    image: ghcr.io/fl3my/document-vision-service:latest
    depends_on:
      - wimpeytrack-api
    restart: unless-stopped
    networks: 
      - proxy

  osrm-backend:
    image: ghcr.io/project-osrm/osrm-backend:latest
    volumes:
      - /opt/osrm/scotland-osrm:/data:ro
    command: osrm-routed --algorithm mld /data/scotland-latest.osrm
    restart: unless-stopped
    networks:
      - proxy

volumes:
  wimpeytrack-db:
  wimpeytrack-uploads:
  wimpeytrack-reports:
    
networks:
  proxy:
    external: true