/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * WimpeyTrack.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const getDashboardResponse = zod.object({
  "summary": zod.object({
  "totalClaimedThisTaxYear": zod.coerce.number().optional(),
  "totalClaimedThisMonth": zod.coerce.number().optional(),
  "totalMileageThisTaxYear": zod.coerce.number().optional()
}).optional(),
  "cumulativeMiles": zod.array(zod.object({
  "month": zod.coerce.string().optional(),
  "miles": zod.coerce.number().optional(),
  "claim": zod.coerce.number().optional()
})).optional(),
  "monthlyMiles": zod.array(zod.object({
  "month": zod.coerce.string().optional(),
  "miles": zod.coerce.number().optional(),
  "claim": zod.coerce.number().optional()
})).optional()
})


export const getPurchasesPurchaseIdItemsParams = zod.object({
  "purchaseId": zod.coerce.string()
})

export const getPurchasesPurchaseIdItemsResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})
export const getPurchasesPurchaseIdItemsResponse = zod.array(getPurchasesPurchaseIdItemsResponseItem)


export const postPurchasesPurchaseIdItemsParams = zod.object({
  "purchaseId": zod.coerce.number()
})

export const postPurchasesPurchaseIdItemsBodyNameMin = 3;
export const postPurchasesPurchaseIdItemsBodyNameMax = 50;

export const postPurchasesPurchaseIdItemsBodyQuantityMax = 10;

export const postPurchasesPurchaseIdItemsBodyCostMin = 0.01;
export const postPurchasesPurchaseIdItemsBodyCostMax = 100;

export const postPurchasesPurchaseIdItemsBodyReasonMin = 3;
export const postPurchasesPurchaseIdItemsBodyReasonMax = 50;



export const postPurchasesPurchaseIdItemsBody = zod.object({
  "name": zod.coerce.string().min(postPurchasesPurchaseIdItemsBodyNameMin).max(postPurchasesPurchaseIdItemsBodyNameMax),
  "quantity": zod.coerce.number().min(1).max(postPurchasesPurchaseIdItemsBodyQuantityMax),
  "cost": zod.coerce.number().min(postPurchasesPurchaseIdItemsBodyCostMin).max(postPurchasesPurchaseIdItemsBodyCostMax),
  "reason": zod.coerce.string().min(postPurchasesPurchaseIdItemsBodyReasonMin).max(postPurchasesPurchaseIdItemsBodyReasonMax)
})

export const postPurchasesPurchaseIdItemsResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})


export const getPurchasesPurchaseIdItemsItemIdParams = zod.object({
  "purchaseId": zod.coerce.number(),
  "itemId": zod.coerce.number()
})

export const getPurchasesPurchaseIdItemsItemIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})


export const putPurchasesPurchaseIdItemsItemIdParams = zod.object({
  "purchaseId": zod.coerce.number(),
  "itemId": zod.coerce.number()
})

export const putPurchasesPurchaseIdItemsItemIdBodyNameMin = 3;
export const putPurchasesPurchaseIdItemsItemIdBodyNameMax = 50;

export const putPurchasesPurchaseIdItemsItemIdBodyQuantityMin = 0.01;
export const putPurchasesPurchaseIdItemsItemIdBodyQuantityMax = 10;

export const putPurchasesPurchaseIdItemsItemIdBodyCostMin = 0.01;
export const putPurchasesPurchaseIdItemsItemIdBodyCostMax = 100;

export const putPurchasesPurchaseIdItemsItemIdBodyReasonMin = 3;
export const putPurchasesPurchaseIdItemsItemIdBodyReasonMax = 50;



export const putPurchasesPurchaseIdItemsItemIdBody = zod.object({
  "id": zod.coerce.number(),
  "name": zod.coerce.string().min(putPurchasesPurchaseIdItemsItemIdBodyNameMin).max(putPurchasesPurchaseIdItemsItemIdBodyNameMax),
  "quantity": zod.coerce.number().min(putPurchasesPurchaseIdItemsItemIdBodyQuantityMin).max(putPurchasesPurchaseIdItemsItemIdBodyQuantityMax),
  "cost": zod.coerce.number().min(putPurchasesPurchaseIdItemsItemIdBodyCostMin).max(putPurchasesPurchaseIdItemsItemIdBodyCostMax),
  "reason": zod.coerce.string().min(putPurchasesPurchaseIdItemsItemIdBodyReasonMin).max(putPurchasesPurchaseIdItemsItemIdBodyReasonMax)
})


export const deletePurchasesPurchaseIdItemsItemIdParams = zod.object({
  "purchaseId": zod.coerce.number(),
  "itemId": zod.coerce.number()
})


export const getJourneysQueryParams = zod.object({
  "weekStart": zod.iso.date()
})

export const getJourneysResponse = zod.object({
  "journeys": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "totalMiles": zod.coerce.number().optional(),
  "isManualMiles": zod.coerce.boolean().optional(),
  "homeLocationId": zod.coerce.number().optional(),
  "trips": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "locationName": zod.coerce.string().optional(),
  "reasonName": zod.coerce.string().optional()
})).optional()
})).optional(),
  "startDate": zod.iso.date().optional(),
  "endDate": zod.iso.date().optional()
})


export const postJourneysBodyTotalMilesMax = 300;



export const postJourneysBody = zod.object({
  "date": zod.iso.date(),
  "totalMiles": zod.coerce.number().min(1).max(postJourneysBodyTotalMilesMax),
  "isManualMiles": zod.coerce.boolean(),
  "homeLocationId": zod.coerce.number()
})

export const postJourneysResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "totalMiles": zod.coerce.number().optional(),
  "isManualMiles": zod.coerce.boolean().optional(),
  "homeLocationId": zod.coerce.number().optional(),
  "trips": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "locationName": zod.coerce.string().optional(),
  "reasonName": zod.coerce.string().optional()
})).optional()
})


export const getJourneysIdParams = zod.object({
  "id": zod.coerce.number()
})

export const getJourneysIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "totalMiles": zod.coerce.number().optional(),
  "isManualMiles": zod.coerce.boolean().optional(),
  "homeLocationId": zod.coerce.number().optional(),
  "trips": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "locationName": zod.coerce.string().optional(),
  "reasonName": zod.coerce.string().optional()
})).optional()
})


export const putJourneysIdParams = zod.object({
  "id": zod.coerce.number()
})

export const putJourneysIdBodyTotalMilesMax = 300;



export const putJourneysIdBody = zod.object({
  "id": zod.coerce.number(),
  "date": zod.iso.date(),
  "totalMiles": zod.coerce.number().min(1).max(putJourneysIdBodyTotalMilesMax),
  "isManualMiles": zod.coerce.boolean(),
  "homeLocationId": zod.coerce.number()
})


export const deleteJourneysIdParams = zod.object({
  "id": zod.coerce.number()
})


export const getLocationsResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "latitude": zod.coerce.number().optional(),
  "longitude": zod.coerce.number().optional()
})
export const getLocationsResponse = zod.array(getLocationsResponseItem)


export const postLocationsBodyNameMin = 3;
export const postLocationsBodyNameMax = 50;

export const postLocationsBodyLatitudeMin = 55.3669;
export const postLocationsBodyLatitudeMax = 56.1059;

export const postLocationsBodyLongitudeMin = -4.9821;
export const postLocationsBodyLongitudeMax = -2.6953;



export const postLocationsBody = zod.object({
  "name": zod.coerce.string().min(postLocationsBodyNameMin).max(postLocationsBodyNameMax),
  "latitude": zod.coerce.number().min(postLocationsBodyLatitudeMin).max(postLocationsBodyLatitudeMax),
  "longitude": zod.coerce.number().min(postLocationsBodyLongitudeMin).max(postLocationsBodyLongitudeMax)
})

export const postLocationsResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "latitude": zod.coerce.number().optional(),
  "longitude": zod.coerce.number().optional()
})


export const getLocationsIdParams = zod.object({
  "id": zod.coerce.number()
})

export const getLocationsIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "latitude": zod.coerce.number().optional(),
  "longitude": zod.coerce.number().optional()
})


export const putLocationsIdParams = zod.object({
  "id": zod.coerce.number()
})

export const putLocationsIdBodyNameMin = 3;
export const putLocationsIdBodyNameMax = 50;

export const putLocationsIdBodyLatitudeMin = 55.3669;
export const putLocationsIdBodyLatitudeMax = 56.1059;

export const putLocationsIdBodyLongitudeMin = -4.9821;
export const putLocationsIdBodyLongitudeMax = -2.6953;



export const putLocationsIdBody = zod.object({
  "id": zod.coerce.number(),
  "name": zod.coerce.string().min(putLocationsIdBodyNameMin).max(putLocationsIdBodyNameMax),
  "latitude": zod.coerce.number().min(putLocationsIdBodyLatitudeMin).max(putLocationsIdBodyLatitudeMax),
  "longitude": zod.coerce.number().min(putLocationsIdBodyLongitudeMin).max(putLocationsIdBodyLongitudeMax)
})


export const deleteLocationsIdParams = zod.object({
  "id": zod.coerce.number()
})


export const getPurchasesResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "storeName": zod.coerce.string().optional(),
  "items": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})).optional()
})
export const getPurchasesResponse = zod.array(getPurchasesResponseItem)


export const postPurchasesBodyStoreNameMin = 3;
export const postPurchasesBodyStoreNameMax = 50;

export const postPurchasesBodyItemsItemNameMin = 3;
export const postPurchasesBodyItemsItemNameMax = 50;

export const postPurchasesBodyItemsItemQuantityMax = 10;

export const postPurchasesBodyItemsItemCostMin = 0.01;
export const postPurchasesBodyItemsItemCostMax = 100;

export const postPurchasesBodyItemsItemReasonMin = 3;
export const postPurchasesBodyItemsItemReasonMax = 50;




export const postPurchasesBody = zod.object({
  "date": zod.iso.date(),
  "storeName": zod.coerce.string().min(postPurchasesBodyStoreNameMin).max(postPurchasesBodyStoreNameMax),
  "receiptId": zod.coerce.number().nullish(),
  "items": zod.array(zod.object({
  "name": zod.coerce.string().min(postPurchasesBodyItemsItemNameMin).max(postPurchasesBodyItemsItemNameMax),
  "quantity": zod.coerce.number().min(1).max(postPurchasesBodyItemsItemQuantityMax),
  "cost": zod.coerce.number().min(postPurchasesBodyItemsItemCostMin).max(postPurchasesBodyItemsItemCostMax),
  "reason": zod.coerce.string().min(postPurchasesBodyItemsItemReasonMin).max(postPurchasesBodyItemsItemReasonMax)
})).min(1)
})

export const postPurchasesResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "storeName": zod.coerce.string().optional(),
  "items": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})).optional()
})


export const getPurchasesIdParams = zod.object({
  "id": zod.coerce.number()
})

export const getPurchasesIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "storeName": zod.coerce.string().optional(),
  "items": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})).optional()
})


export const putPurchasesIdParams = zod.object({
  "id": zod.coerce.number()
})

export const putPurchasesIdBodyStoreNameMin = 3;
export const putPurchasesIdBodyStoreNameMax = 50;



export const putPurchasesIdBody = zod.object({
  "id": zod.coerce.number(),
  "date": zod.iso.date(),
  "storeName": zod.coerce.string().min(putPurchasesIdBodyStoreNameMin).max(putPurchasesIdBodyStoreNameMax)
})


export const deletePurchasesIdParams = zod.object({
  "id": zod.coerce.number()
})


export const getReasonsResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional()
})
export const getReasonsResponse = zod.array(getReasonsResponseItem)


export const postReasonsBodyNameMin = 2;
export const postReasonsBodyNameMax = 50;



export const postReasonsBody = zod.object({
  "name": zod.coerce.string().min(postReasonsBodyNameMin).max(postReasonsBodyNameMax)
})

export const postReasonsResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional()
})


export const getReasonsIdParams = zod.object({
  "id": zod.coerce.number()
})

export const getReasonsIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional()
})


export const putReasonsIdParams = zod.object({
  "id": zod.coerce.number()
})

export const putReasonsIdBodyNameMin = 2;
export const putReasonsIdBodyNameMax = 50;



export const putReasonsIdBody = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().min(putReasonsIdBodyNameMin).max(putReasonsIdBodyNameMax)
})


export const deleteReasonsIdParams = zod.object({
  "id": zod.coerce.number()
})


export const getReceiptsResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "category": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "imagePath": zod.coerce.string().optional(),
  "purchase": zod.union([zod.null(),zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "storeName": zod.coerce.string().optional(),
  "items": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional(),
  "purchaseId": zod.coerce.number().optional(),
  "purchase": zod.unknown().optional()
})).optional(),
  "receiptId": zod.coerce.number().nullish(),
  "receipt": zod.union([zod.null(),zod.unknown()]).optional()
})]).optional()
})
export const getReceiptsResponse = zod.array(getReceiptsResponseItem)


export const postReceiptsBodyNameMin = 2;
export const postReceiptsBodyNameMax = 50;



export const postReceiptsBody = zod.object({
  "Name": zod.coerce.string().min(postReceiptsBodyNameMin).max(postReceiptsBodyNameMax).optional(),
  "Date": zod.iso.date().optional(),
  "Category": zod.coerce.number().optional(),
  "File": zod.instanceof(File).optional()
})

export const postReceiptsResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "date": zod.iso.date().optional(),
  "category": zod.coerce.number().optional(),
  "imagePath": zod.coerce.string().optional(),
  "purchaseId": zod.coerce.number().nullish()
})


export const getReceiptsIdParams = zod.object({
  "id": zod.coerce.number()
})

export const getReceiptsIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "date": zod.iso.date().optional(),
  "category": zod.coerce.number().optional(),
  "imagePath": zod.coerce.string().optional(),
  "purchaseId": zod.coerce.number().nullish()
})


export const deleteReceiptsIdParams = zod.object({
  "id": zod.coerce.number()
})


export const postReceiptsFuelBodyNameMin = 2;
export const postReceiptsFuelBodyNameMax = 50;



export const postReceiptsFuelBody = zod.object({
  "name": zod.coerce.string().min(postReceiptsFuelBodyNameMin).max(postReceiptsFuelBodyNameMax),
  "date": zod.iso.date(),
  "base64Content": zod.coerce.string()
})

export const postReceiptsFuelResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "date": zod.iso.date().optional(),
  "category": zod.coerce.number().optional(),
  "imagePath": zod.coerce.string().optional(),
  "purchaseId": zod.coerce.number().nullish()
})


export const postReceiptsPurchaseBodyPurchaseStoreNameMin = 3;
export const postReceiptsPurchaseBodyPurchaseStoreNameMax = 50;

export const postReceiptsPurchaseBodyPurchaseItemsItemNameMin = 3;
export const postReceiptsPurchaseBodyPurchaseItemsItemNameMax = 50;

export const postReceiptsPurchaseBodyPurchaseItemsItemQuantityMax = 10;

export const postReceiptsPurchaseBodyPurchaseItemsItemCostMin = 0.01;
export const postReceiptsPurchaseBodyPurchaseItemsItemCostMax = 100;

export const postReceiptsPurchaseBodyPurchaseItemsItemReasonMin = 3;
export const postReceiptsPurchaseBodyPurchaseItemsItemReasonMax = 50;


export const postReceiptsPurchaseBodyNameMin = 2;
export const postReceiptsPurchaseBodyNameMax = 50;



export const postReceiptsPurchaseBody = zod.object({
  "purchase": zod.object({
  "date": zod.iso.date(),
  "storeName": zod.coerce.string().min(postReceiptsPurchaseBodyPurchaseStoreNameMin).max(postReceiptsPurchaseBodyPurchaseStoreNameMax),
  "receiptId": zod.coerce.number().nullish(),
  "items": zod.array(zod.object({
  "name": zod.coerce.string().min(postReceiptsPurchaseBodyPurchaseItemsItemNameMin).max(postReceiptsPurchaseBodyPurchaseItemsItemNameMax),
  "quantity": zod.coerce.number().min(1).max(postReceiptsPurchaseBodyPurchaseItemsItemQuantityMax),
  "cost": zod.coerce.number().min(postReceiptsPurchaseBodyPurchaseItemsItemCostMin).max(postReceiptsPurchaseBodyPurchaseItemsItemCostMax),
  "reason": zod.coerce.string().min(postReceiptsPurchaseBodyPurchaseItemsItemReasonMin).max(postReceiptsPurchaseBodyPurchaseItemsItemReasonMax)
})).min(1)
}).optional(),
  "name": zod.coerce.string().min(postReceiptsPurchaseBodyNameMin).max(postReceiptsPurchaseBodyNameMax),
  "date": zod.iso.date(),
  "base64Content": zod.coerce.string()
})

export const postReceiptsPurchaseResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "date": zod.iso.date().optional(),
  "category": zod.coerce.number().optional(),
  "imagePath": zod.coerce.string().optional(),
  "purchaseId": zod.coerce.number().nullish()
})


export const postReceiptsOcrBody = zod.object({
  "File": zod.instanceof(File).optional()
})

export const postReceiptsOcrResponse = zod.object({
  "imageBase64": zod.coerce.string().optional(),
  "receiptData": zod.array(zod.object({
  "storeName": zod.coerce.string().optional(),
  "transactionDate": zod.iso.date().nullish(),
  "receiptCategory": zod.coerce.number().optional(),
  "receiptItems": zod.array(zod.object({
  "description": zod.coerce.string().nullish(),
  "price": zod.coerce.number().nullish(),
  "quantity": zod.coerce.number().nullish()
})).optional(),
  "boundingBox": zod.union([zod.null(),zod.object({
  "x": zod.coerce.number().optional(),
  "y": zod.coerce.number().optional(),
  "width": zod.coerce.number().optional(),
  "height": zod.coerce.number().optional()
})]).optional()
})).optional()
})


export const getReportResponseItem = zod.object({
  "id": zod.uuid().optional(),
  "startDate": zod.iso.date().optional(),
  "endDate": zod.iso.date().optional(),
  "generatedAtUtc": zod.iso.datetime({}).optional(),
  "folderPath": zod.coerce.string().optional()
})
export const getReportResponse = zod.array(getReportResponseItem)


export const postReportQueryParams = zod.object({
  "startDate": zod.iso.date().optional(),
  "endDate": zod.iso.date().optional()
})

export const postReportResponse = zod.object({
  "reportId": zod.coerce.string().optional()
})


export const deleteReportIdParams = zod.object({
  "id": zod.uuid()
})


export const getReportIdParams = zod.object({
  "id": zod.uuid()
})

export const getReportIdResponse = zod.object({
  "reportId": zod.uuid().optional(),
  "expenseDocuments": zod.array(zod.object({
  "fileName": zod.coerce.string().optional(),
  "url": zod.coerce.string().optional()
})).optional(),
  "receiptPages": zod.array(zod.object({
  "fileName": zod.coerce.string().optional(),
  "url": zod.coerce.string().optional()
})).optional()
})


export const getJourneysJourneyIdTripsParams = zod.object({
  "journeyId": zod.coerce.number()
})

export const getJourneysJourneyIdTripsResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "locationId": zod.coerce.number().optional(),
  "reasonId": zod.coerce.number().optional()
})
export const getJourneysJourneyIdTripsResponse = zod.array(getJourneysJourneyIdTripsResponseItem)


export const postJourneysJourneyIdTripsParams = zod.object({
  "journeyId": zod.coerce.number()
})

export const postJourneysJourneyIdTripsBody = zod.object({
  "locationId": zod.coerce.number(),
  "reasonId": zod.coerce.number()
})

export const postJourneysJourneyIdTripsResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "locationId": zod.coerce.number().optional(),
  "reasonId": zod.coerce.number().optional()
})


export const getJourneysJourneyIdTripsTripIdParams = zod.object({
  "journeyId": zod.coerce.number(),
  "tripId": zod.coerce.number()
})

export const getJourneysJourneyIdTripsTripIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "locationId": zod.coerce.number().optional(),
  "reasonId": zod.coerce.number().optional()
})


export const putJourneysJourneyIdTripsTripIdParams = zod.object({
  "journeyId": zod.coerce.number(),
  "tripId": zod.coerce.number()
})

export const putJourneysJourneyIdTripsTripIdBody = zod.object({
  "id": zod.coerce.number(),
  "locationId": zod.coerce.number(),
  "reasonId": zod.coerce.number()
})


export const deleteJourneysJourneyIdTripsTripIdParams = zod.object({
  "journeyId": zod.coerce.number(),
  "tripId": zod.coerce.number()
})
