/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * WimpeyTrack.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const getApiDashboardResponse = zod.object({
  "summary": zod.object({
  "totalClaimedThisTaxYear": zod.coerce.number().optional(),
  "totalClaimedThisMonth": zod.coerce.number().optional(),
  "totalMileageThisTaxYear": zod.coerce.number().optional()
}).optional(),
  "cumulativeMiles": zod.array(zod.object({
  "month": zod.coerce.string().optional(),
  "miles": zod.coerce.number().optional(),
  "claim": zod.coerce.number().optional()
})).optional(),
  "monthlyMiles": zod.array(zod.object({
  "month": zod.coerce.string().optional(),
  "miles": zod.coerce.number().optional(),
  "claim": zod.coerce.number().optional()
})).optional()
})


export const getApiEmailRecipientsResponseItem = zod.object({
  "id": zod.coerce.number(),
  "firstName": zod.coerce.string(),
  "lastName": zod.coerce.string(),
  "email": zod.coerce.string()
})
export const getApiEmailRecipientsResponse = zod.array(getApiEmailRecipientsResponseItem)


export const postApiEmailRecipientsBody = zod.object({
  "firstName": zod.coerce.string(),
  "lastName": zod.coerce.string(),
  "email": zod.coerce.string()
})

export const postApiEmailRecipientsResponse = zod.object({
  "id": zod.coerce.number(),
  "firstName": zod.coerce.string(),
  "lastName": zod.coerce.string(),
  "email": zod.coerce.string()
})


export const getApiEmailRecipientsIdParams = zod.object({
  "id": zod.coerce.number()
})

export const getApiEmailRecipientsIdResponse = zod.object({
  "id": zod.coerce.number(),
  "firstName": zod.coerce.string(),
  "lastName": zod.coerce.string(),
  "email": zod.coerce.string()
})


export const deleteApiEmailRecipientsIdParams = zod.object({
  "id": zod.coerce.number()
})


export const getApiPurchasesPurchaseIdItemsParams = zod.object({
  "purchaseId": zod.coerce.string()
})

export const getApiPurchasesPurchaseIdItemsResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})
export const getApiPurchasesPurchaseIdItemsResponse = zod.array(getApiPurchasesPurchaseIdItemsResponseItem)


export const postApiPurchasesPurchaseIdItemsParams = zod.object({
  "purchaseId": zod.coerce.number()
})

export const postApiPurchasesPurchaseIdItemsBodyNameMin = 3;
export const postApiPurchasesPurchaseIdItemsBodyNameMax = 50;

export const postApiPurchasesPurchaseIdItemsBodyQuantityMax = 10;

export const postApiPurchasesPurchaseIdItemsBodyCostMin = 0.01;
export const postApiPurchasesPurchaseIdItemsBodyCostMax = 100;

export const postApiPurchasesPurchaseIdItemsBodyReasonMin = 3;
export const postApiPurchasesPurchaseIdItemsBodyReasonMax = 50;



export const postApiPurchasesPurchaseIdItemsBody = zod.object({
  "name": zod.coerce.string().min(postApiPurchasesPurchaseIdItemsBodyNameMin).max(postApiPurchasesPurchaseIdItemsBodyNameMax),
  "quantity": zod.coerce.number().min(1).max(postApiPurchasesPurchaseIdItemsBodyQuantityMax),
  "cost": zod.coerce.number().min(postApiPurchasesPurchaseIdItemsBodyCostMin).max(postApiPurchasesPurchaseIdItemsBodyCostMax),
  "reason": zod.coerce.string().min(postApiPurchasesPurchaseIdItemsBodyReasonMin).max(postApiPurchasesPurchaseIdItemsBodyReasonMax)
})

export const postApiPurchasesPurchaseIdItemsResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})


export const getApiPurchasesPurchaseIdItemsItemIdParams = zod.object({
  "purchaseId": zod.coerce.number(),
  "itemId": zod.coerce.number()
})

export const getApiPurchasesPurchaseIdItemsItemIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})


export const putApiPurchasesPurchaseIdItemsItemIdParams = zod.object({
  "purchaseId": zod.coerce.number(),
  "itemId": zod.coerce.number()
})

export const putApiPurchasesPurchaseIdItemsItemIdBodyNameMin = 3;
export const putApiPurchasesPurchaseIdItemsItemIdBodyNameMax = 50;

export const putApiPurchasesPurchaseIdItemsItemIdBodyQuantityMin = 0.01;
export const putApiPurchasesPurchaseIdItemsItemIdBodyQuantityMax = 10;

export const putApiPurchasesPurchaseIdItemsItemIdBodyCostMin = 0.01;
export const putApiPurchasesPurchaseIdItemsItemIdBodyCostMax = 100;

export const putApiPurchasesPurchaseIdItemsItemIdBodyReasonMin = 3;
export const putApiPurchasesPurchaseIdItemsItemIdBodyReasonMax = 50;



export const putApiPurchasesPurchaseIdItemsItemIdBody = zod.object({
  "id": zod.coerce.number(),
  "name": zod.coerce.string().min(putApiPurchasesPurchaseIdItemsItemIdBodyNameMin).max(putApiPurchasesPurchaseIdItemsItemIdBodyNameMax),
  "quantity": zod.coerce.number().min(putApiPurchasesPurchaseIdItemsItemIdBodyQuantityMin).max(putApiPurchasesPurchaseIdItemsItemIdBodyQuantityMax),
  "cost": zod.coerce.number().min(putApiPurchasesPurchaseIdItemsItemIdBodyCostMin).max(putApiPurchasesPurchaseIdItemsItemIdBodyCostMax),
  "reason": zod.coerce.string().min(putApiPurchasesPurchaseIdItemsItemIdBodyReasonMin).max(putApiPurchasesPurchaseIdItemsItemIdBodyReasonMax)
})


export const deleteApiPurchasesPurchaseIdItemsItemIdParams = zod.object({
  "purchaseId": zod.coerce.number(),
  "itemId": zod.coerce.number()
})


export const getApiJourneysQueryParams = zod.object({
  "weekStart": zod.iso.date().optional()
})

export const getApiJourneysResponse = zod.object({
  "weekStart": zod.iso.date(),
  "prevWeekStart": zod.iso.date(),
  "nextWeekStart": zod.iso.date(),
  "days": zod.array(zod.object({
  "date": zod.iso.date(),
  "journey": zod.union([zod.null(),zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "totalMiles": zod.coerce.number().optional(),
  "isManualMiles": zod.coerce.boolean().optional(),
  "homeLocationId": zod.coerce.number().optional(),
  "homeLocationName": zod.coerce.string().optional(),
  "trips": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "locationName": zod.coerce.string().optional(),
  "reasonName": zod.coerce.string().optional()
})).optional()
})])
}))
})


export const postApiJourneysBodyTripsMax = 10;



export const postApiJourneysBody = zod.object({
  "date": zod.iso.date(),
  "trips": zod.array(zod.object({
  "locationId": zod.coerce.number(),
  "reasonId": zod.coerce.number()
})).min(1).max(postApiJourneysBodyTripsMax)
})

export const postApiJourneysResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "totalMiles": zod.coerce.number().optional(),
  "isManualMiles": zod.coerce.boolean().optional(),
  "homeLocationId": zod.coerce.number().optional(),
  "homeLocationName": zod.coerce.string().optional(),
  "trips": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "locationName": zod.coerce.string().optional(),
  "reasonName": zod.coerce.string().optional()
})).optional()
})


export const getApiJourneysIdParams = zod.object({
  "id": zod.coerce.number()
})

export const getApiJourneysIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "totalMiles": zod.coerce.number().optional(),
  "isManualMiles": zod.coerce.boolean().optional(),
  "homeLocationId": zod.coerce.number().optional(),
  "homeLocationName": zod.coerce.string().optional(),
  "trips": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "locationName": zod.coerce.string().optional(),
  "reasonName": zod.coerce.string().optional()
})).optional()
})


export const putApiJourneysIdParams = zod.object({
  "id": zod.coerce.number()
})

export const putApiJourneysIdBodyTotalMilesMax = 300;



export const putApiJourneysIdBody = zod.object({
  "id": zod.coerce.number(),
  "date": zod.iso.date(),
  "totalMiles": zod.coerce.number().min(1).max(putApiJourneysIdBodyTotalMilesMax),
  "isManualMiles": zod.coerce.boolean(),
  "homeLocationId": zod.coerce.number()
})


export const deleteApiJourneysIdParams = zod.object({
  "id": zod.coerce.number()
})


export const getApiLocationsQuerySortByDefault = 1;

export const getApiLocationsQueryParams = zod.object({
  "sortBy": zod.coerce.number().default(getApiLocationsQuerySortByDefault)
})

export const getApiLocationsResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "tripCount": zod.coerce.number().optional(),
  "latitude": zod.coerce.number().optional(),
  "longitude": zod.coerce.number().optional()
})
export const getApiLocationsResponse = zod.array(getApiLocationsResponseItem)


export const postApiLocationsBodyNameMin = 3;
export const postApiLocationsBodyNameMax = 50;

export const postApiLocationsBodyLatitudeMin = 55.3669;
export const postApiLocationsBodyLatitudeMax = 56.1059;

export const postApiLocationsBodyLongitudeMin = -4.9821;
export const postApiLocationsBodyLongitudeMax = -2.6953;



export const postApiLocationsBody = zod.object({
  "name": zod.coerce.string().min(postApiLocationsBodyNameMin).max(postApiLocationsBodyNameMax),
  "latitude": zod.coerce.number().min(postApiLocationsBodyLatitudeMin).max(postApiLocationsBodyLatitudeMax),
  "longitude": zod.coerce.number().min(postApiLocationsBodyLongitudeMin).max(postApiLocationsBodyLongitudeMax)
})

export const postApiLocationsResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "tripCount": zod.coerce.number().optional(),
  "latitude": zod.coerce.number().optional(),
  "longitude": zod.coerce.number().optional()
})


export const getApiLocationsIdParams = zod.object({
  "id": zod.coerce.number()
})

export const getApiLocationsIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "tripCount": zod.coerce.number().optional(),
  "latitude": zod.coerce.number().optional(),
  "longitude": zod.coerce.number().optional()
})


export const putApiLocationsIdParams = zod.object({
  "id": zod.coerce.number()
})

export const putApiLocationsIdBodyNameMin = 3;
export const putApiLocationsIdBodyNameMax = 50;

export const putApiLocationsIdBodyLatitudeMin = 55.3669;
export const putApiLocationsIdBodyLatitudeMax = 56.1059;

export const putApiLocationsIdBodyLongitudeMin = -4.9821;
export const putApiLocationsIdBodyLongitudeMax = -2.6953;



export const putApiLocationsIdBody = zod.object({
  "id": zod.coerce.number(),
  "name": zod.coerce.string().min(putApiLocationsIdBodyNameMin).max(putApiLocationsIdBodyNameMax),
  "latitude": zod.coerce.number().min(putApiLocationsIdBodyLatitudeMin).max(putApiLocationsIdBodyLatitudeMax),
  "longitude": zod.coerce.number().min(putApiLocationsIdBodyLongitudeMin).max(putApiLocationsIdBodyLongitudeMax)
})


export const deleteApiLocationsIdParams = zod.object({
  "id": zod.coerce.number()
})


export const getApiPreferenceResponse = zod.object({
  "milesAdjustmentFactor": zod.coerce.number()
})


export const putApiPreferenceBodyMilesAdjustmentFactorMin = 0.5;
export const putApiPreferenceBodyMilesAdjustmentFactorMax = 2;



export const putApiPreferenceBody = zod.object({
  "milesAdjustmentFactor": zod.coerce.number().min(putApiPreferenceBodyMilesAdjustmentFactorMin).max(putApiPreferenceBodyMilesAdjustmentFactorMax)
})


export const getApiProfileResponse = zod.object({
  "fullName": zod.coerce.string(),
  "staffNumber": zod.coerce.string(),
  "businessUnit": zod.coerce.string(),
  "departmentSiteName": zod.coerce.string(),
  "vehicleFuelType": zod.coerce.string(),
  "vehicleEngineSize": zod.coerce.number(),
  "vehicleRegistration": zod.coerce.string(),
  "vehicleMake": zod.coerce.string(),
  "homePostcode": zod.coerce.string(),
  "homeLocationId": zod.coerce.number()
})


export const putApiProfileBody = zod.object({
  "fullName": zod.coerce.string().optional(),
  "staffNumber": zod.coerce.string().optional(),
  "businessUnit": zod.coerce.string().optional(),
  "departmentSiteName": zod.coerce.string().optional(),
  "vehicleFuelType": zod.coerce.string().optional(),
  "vehicleEngineSize": zod.coerce.number().optional(),
  "vehicleRegistration": zod.coerce.string().optional(),
  "vehicleMake": zod.coerce.string().optional(),
  "homePostcode": zod.coerce.string().optional(),
  "homeLocationId": zod.coerce.number().optional()
})


export const getApiPurchasesResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "storeName": zod.coerce.string().optional(),
  "items": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})).optional()
})
export const getApiPurchasesResponse = zod.array(getApiPurchasesResponseItem)


export const postApiPurchasesBodyStoreNameMin = 3;
export const postApiPurchasesBodyStoreNameMax = 50;

export const postApiPurchasesBodyItemsItemNameMin = 3;
export const postApiPurchasesBodyItemsItemNameMax = 50;

export const postApiPurchasesBodyItemsItemQuantityMax = 10;

export const postApiPurchasesBodyItemsItemCostMin = 0.01;
export const postApiPurchasesBodyItemsItemCostMax = 100;

export const postApiPurchasesBodyItemsItemReasonMin = 3;
export const postApiPurchasesBodyItemsItemReasonMax = 50;




export const postApiPurchasesBody = zod.object({
  "date": zod.iso.date(),
  "storeName": zod.coerce.string().min(postApiPurchasesBodyStoreNameMin).max(postApiPurchasesBodyStoreNameMax),
  "receiptId": zod.coerce.number().nullish(),
  "items": zod.array(zod.object({
  "name": zod.coerce.string().min(postApiPurchasesBodyItemsItemNameMin).max(postApiPurchasesBodyItemsItemNameMax),
  "quantity": zod.coerce.number().min(1).max(postApiPurchasesBodyItemsItemQuantityMax),
  "cost": zod.coerce.number().min(postApiPurchasesBodyItemsItemCostMin).max(postApiPurchasesBodyItemsItemCostMax),
  "reason": zod.coerce.string().min(postApiPurchasesBodyItemsItemReasonMin).max(postApiPurchasesBodyItemsItemReasonMax)
})).min(1)
})

export const postApiPurchasesResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "storeName": zod.coerce.string().optional(),
  "items": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})).optional()
})


export const getApiPurchasesIdParams = zod.object({
  "id": zod.coerce.number()
})

export const getApiPurchasesIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "storeName": zod.coerce.string().optional(),
  "items": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional()
})).optional()
})


export const putApiPurchasesIdParams = zod.object({
  "id": zod.coerce.number()
})

export const putApiPurchasesIdBodyStoreNameMin = 3;
export const putApiPurchasesIdBodyStoreNameMax = 50;



export const putApiPurchasesIdBody = zod.object({
  "id": zod.coerce.number(),
  "date": zod.iso.date(),
  "storeName": zod.coerce.string().min(putApiPurchasesIdBodyStoreNameMin).max(putApiPurchasesIdBodyStoreNameMax)
})


export const deleteApiPurchasesIdParams = zod.object({
  "id": zod.coerce.number()
})


export const getApiReasonsResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "tripCount": zod.coerce.number().optional()
})
export const getApiReasonsResponse = zod.array(getApiReasonsResponseItem)


export const postApiReasonsBodyNameMin = 2;
export const postApiReasonsBodyNameMax = 50;



export const postApiReasonsBody = zod.object({
  "name": zod.coerce.string().min(postApiReasonsBodyNameMin).max(postApiReasonsBodyNameMax)
})

export const postApiReasonsResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "tripCount": zod.coerce.number().optional()
})


export const getApiReasonsIdParams = zod.object({
  "id": zod.coerce.number()
})

export const getApiReasonsIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "tripCount": zod.coerce.number().optional()
})


export const putApiReasonsIdParams = zod.object({
  "id": zod.coerce.number()
})

export const putApiReasonsIdBodyNameMin = 2;
export const putApiReasonsIdBodyNameMax = 50;



export const putApiReasonsIdBody = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().min(putApiReasonsIdBodyNameMin).max(putApiReasonsIdBodyNameMax)
})


export const deleteApiReasonsIdParams = zod.object({
  "id": zod.coerce.number()
})


export const getApiReceiptsResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "category": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "imagePath": zod.coerce.string().optional(),
  "purchase": zod.union([zod.null(),zod.object({
  "id": zod.coerce.number().optional(),
  "date": zod.iso.date().optional(),
  "storeName": zod.coerce.string().optional(),
  "items": zod.array(zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "quantity": zod.coerce.number().optional(),
  "cost": zod.coerce.number().optional(),
  "reason": zod.coerce.string().optional(),
  "purchaseId": zod.coerce.number().optional(),
  "purchase": zod.unknown().optional()
})).optional(),
  "receiptId": zod.coerce.number().nullish(),
  "receipt": zod.union([zod.null(),zod.unknown()]).optional()
})]).optional()
})
export const getApiReceiptsResponse = zod.array(getApiReceiptsResponseItem)


export const postApiReceiptsBodyNameMin = 2;
export const postApiReceiptsBodyNameMax = 50;



export const postApiReceiptsBody = zod.object({
  "Name": zod.coerce.string().min(postApiReceiptsBodyNameMin).max(postApiReceiptsBodyNameMax).optional(),
  "Date": zod.iso.date().optional(),
  "Category": zod.coerce.number().optional(),
  "File": zod.instanceof(File).optional()
})

export const postApiReceiptsResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "date": zod.iso.date().optional(),
  "category": zod.coerce.number().optional(),
  "imagePath": zod.coerce.string().optional(),
  "purchaseId": zod.coerce.number().nullish()
})


export const getApiReceiptsIdParams = zod.object({
  "id": zod.coerce.number()
})

export const getApiReceiptsIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "date": zod.iso.date().optional(),
  "category": zod.coerce.number().optional(),
  "imagePath": zod.coerce.string().optional(),
  "purchaseId": zod.coerce.number().nullish()
})


export const deleteApiReceiptsIdParams = zod.object({
  "id": zod.coerce.number()
})


export const postApiReceiptsFuelBodyNameMin = 2;
export const postApiReceiptsFuelBodyNameMax = 50;



export const postApiReceiptsFuelBody = zod.object({
  "name": zod.coerce.string().min(postApiReceiptsFuelBodyNameMin).max(postApiReceiptsFuelBodyNameMax),
  "date": zod.iso.date(),
  "base64Content": zod.coerce.string()
})

export const postApiReceiptsFuelResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "date": zod.iso.date().optional(),
  "category": zod.coerce.number().optional(),
  "imagePath": zod.coerce.string().optional(),
  "purchaseId": zod.coerce.number().nullish()
})


export const postApiReceiptsPurchaseBodyPurchaseStoreNameMin = 3;
export const postApiReceiptsPurchaseBodyPurchaseStoreNameMax = 50;

export const postApiReceiptsPurchaseBodyPurchaseItemsItemNameMin = 3;
export const postApiReceiptsPurchaseBodyPurchaseItemsItemNameMax = 50;

export const postApiReceiptsPurchaseBodyPurchaseItemsItemQuantityMax = 10;

export const postApiReceiptsPurchaseBodyPurchaseItemsItemCostMin = 0.01;
export const postApiReceiptsPurchaseBodyPurchaseItemsItemCostMax = 100;

export const postApiReceiptsPurchaseBodyPurchaseItemsItemReasonMin = 3;
export const postApiReceiptsPurchaseBodyPurchaseItemsItemReasonMax = 50;


export const postApiReceiptsPurchaseBodyNameMin = 2;
export const postApiReceiptsPurchaseBodyNameMax = 50;



export const postApiReceiptsPurchaseBody = zod.object({
  "purchase": zod.object({
  "date": zod.iso.date(),
  "storeName": zod.coerce.string().min(postApiReceiptsPurchaseBodyPurchaseStoreNameMin).max(postApiReceiptsPurchaseBodyPurchaseStoreNameMax),
  "receiptId": zod.coerce.number().nullish(),
  "items": zod.array(zod.object({
  "name": zod.coerce.string().min(postApiReceiptsPurchaseBodyPurchaseItemsItemNameMin).max(postApiReceiptsPurchaseBodyPurchaseItemsItemNameMax),
  "quantity": zod.coerce.number().min(1).max(postApiReceiptsPurchaseBodyPurchaseItemsItemQuantityMax),
  "cost": zod.coerce.number().min(postApiReceiptsPurchaseBodyPurchaseItemsItemCostMin).max(postApiReceiptsPurchaseBodyPurchaseItemsItemCostMax),
  "reason": zod.coerce.string().min(postApiReceiptsPurchaseBodyPurchaseItemsItemReasonMin).max(postApiReceiptsPurchaseBodyPurchaseItemsItemReasonMax)
})).min(1)
}).optional(),
  "name": zod.coerce.string().min(postApiReceiptsPurchaseBodyNameMin).max(postApiReceiptsPurchaseBodyNameMax),
  "date": zod.iso.date(),
  "base64Content": zod.coerce.string()
})

export const postApiReceiptsPurchaseResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "name": zod.coerce.string().optional(),
  "date": zod.iso.date().optional(),
  "category": zod.coerce.number().optional(),
  "imagePath": zod.coerce.string().optional(),
  "purchaseId": zod.coerce.number().nullish()
})


export const postApiReceiptsOcrBody = zod.object({
  "File": zod.instanceof(File).optional()
})

export const postApiReceiptsOcrResponse = zod.object({
  "imageBase64": zod.coerce.string().optional(),
  "receiptData": zod.array(zod.object({
  "storeName": zod.coerce.string().optional(),
  "transactionDate": zod.iso.date().nullish(),
  "receiptCategory": zod.coerce.number().optional(),
  "receiptItems": zod.array(zod.object({
  "description": zod.coerce.string().nullish(),
  "price": zod.coerce.number().nullish(),
  "quantity": zod.coerce.number().nullish()
})).optional(),
  "boundingBox": zod.union([zod.null(),zod.object({
  "x": zod.coerce.number().optional(),
  "y": zod.coerce.number().optional(),
  "width": zod.coerce.number().optional(),
  "height": zod.coerce.number().optional()
})]).optional()
})).optional()
})


export const getApiReportResponseItem = zod.object({
  "id": zod.uuid().optional(),
  "startDate": zod.iso.date().optional(),
  "endDate": zod.iso.date().optional(),
  "generatedAtUtc": zod.iso.datetime({}).optional(),
  "folderPath": zod.coerce.string().optional()
})
export const getApiReportResponse = zod.array(getApiReportResponseItem)


export const postApiReportQueryParams = zod.object({
  "startDate": zod.iso.date().optional(),
  "endDate": zod.iso.date().optional()
})

export const postApiReportResponse = zod.object({
  "reportId": zod.coerce.string().optional()
})


export const deleteApiReportIdParams = zod.object({
  "id": zod.uuid()
})


export const getApiReportIdParams = zod.object({
  "id": zod.uuid()
})

export const getApiReportIdResponse = zod.object({
  "reportId": zod.uuid().optional(),
  "startDate": zod.iso.date().optional(),
  "endDate": zod.iso.date().optional(),
  "expenseDocuments": zod.array(zod.object({
  "fileName": zod.coerce.string().optional(),
  "url": zod.coerce.string().optional()
})).optional(),
  "receiptPages": zod.array(zod.object({
  "fileName": zod.coerce.string().optional(),
  "url": zod.coerce.string().optional()
})).optional()
})


export const getApiJourneysJourneyIdTripsParams = zod.object({
  "journeyId": zod.coerce.number()
})

export const getApiJourneysJourneyIdTripsResponseItem = zod.object({
  "id": zod.coerce.number().optional(),
  "locationId": zod.coerce.number().optional(),
  "reasonId": zod.coerce.number().optional()
})
export const getApiJourneysJourneyIdTripsResponse = zod.array(getApiJourneysJourneyIdTripsResponseItem)


export const postApiJourneysJourneyIdTripsParams = zod.object({
  "journeyId": zod.coerce.number()
})

export const postApiJourneysJourneyIdTripsBody = zod.object({
  "locationId": zod.coerce.number(),
  "reasonId": zod.coerce.number()
})

export const postApiJourneysJourneyIdTripsResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "locationId": zod.coerce.number().optional(),
  "reasonId": zod.coerce.number().optional()
})


export const getApiJourneysJourneyIdTripsTripIdParams = zod.object({
  "journeyId": zod.coerce.number(),
  "tripId": zod.coerce.number()
})

export const getApiJourneysJourneyIdTripsTripIdResponse = zod.object({
  "id": zod.coerce.number().optional(),
  "locationId": zod.coerce.number().optional(),
  "reasonId": zod.coerce.number().optional()
})


export const putApiJourneysJourneyIdTripsTripIdParams = zod.object({
  "journeyId": zod.coerce.number(),
  "tripId": zod.coerce.number()
})

export const putApiJourneysJourneyIdTripsTripIdBody = zod.object({
  "id": zod.coerce.number(),
  "locationId": zod.coerce.number(),
  "reasonId": zod.coerce.number()
})


export const deleteApiJourneysJourneyIdTripsTripIdParams = zod.object({
  "journeyId": zod.coerce.number(),
  "tripId": zod.coerce.number()
})
