// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WimpeyTrack.Api.Data;

#nullable disable

namespace WimpeyTrack.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209111725_AddChangeEmailId")]
    partial class AddChangeEmailId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("WimpeyTrack.Api.Models.EmailRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailRecipients");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualMiles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeLocationId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Preference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("MilesAdjustmentFactor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentSiteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomePostcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleEngineSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleFuelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleRegistration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HomeLocationId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId")
                        .IsUnique();

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Reason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JourneyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReasonId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Item", b =>
                {
                    b.HasOne("WimpeyTrack.Api.Models.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Journey", b =>
                {
                    b.HasOne("WimpeyTrack.Api.Models.Location", "HomeLocation")
                        .WithMany()
                        .HasForeignKey("HomeLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeLocation");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Profile", b =>
                {
                    b.HasOne("WimpeyTrack.Api.Models.Location", "HomeLocation")
                        .WithMany()
                        .HasForeignKey("HomeLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeLocation");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Purchase", b =>
                {
                    b.HasOne("WimpeyTrack.Api.Models.Receipt", "Receipt")
                        .WithOne("Purchase")
                        .HasForeignKey("WimpeyTrack.Api.Models.Purchase", "ReceiptId");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Trip", b =>
                {
                    b.HasOne("WimpeyTrack.Api.Models.Journey", "Journey")
                        .WithMany("Trips")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WimpeyTrack.Api.Models.Location", "Location")
                        .WithMany("Trips")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WimpeyTrack.Api.Models.Reason", "Reason")
                        .WithMany("Trips")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("Location");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Journey", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Location", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Purchase", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Reason", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("WimpeyTrack.Api.Models.Receipt", b =>
                {
                    b.Navigation("Purchase");
                });
#pragma warning restore 612, 618
        }
    }
}
