/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WimpeyTrack.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type CreateJourneyDtoTotalMiles = null | number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type CreateJourneyDtoHomeLocationId = number | string;

export interface CreateJourneyDto {
  date: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalMiles?: CreateJourneyDtoTotalMiles;
  isManualMiles: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  homeLocationId: CreateJourneyDtoHomeLocationId;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type CreateLocationDtoLatitude = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type CreateLocationDtoLongitude = number | string;

export interface CreateLocationDto {
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  latitude: CreateLocationDtoLatitude;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  longitude: CreateLocationDtoLongitude;
}

export interface CreateReasonDto {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name: string;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type CreateTripDtoLocationId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type CreateTripDtoReasonId = number | string;

export interface CreateTripDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  locationId?: CreateTripDtoLocationId;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  reasonId?: CreateTripDtoReasonId;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type JourneyId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type JourneyTotalMiles = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type JourneyHomeLocationId = number | string;

export interface Journey {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: JourneyId;
  date?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalMiles?: JourneyTotalMiles;
  isManualMiles?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  homeLocationId?: JourneyHomeLocationId;
  homeLocation?: Location;
  trips?: Trip[];
}

export interface JourneyByWeekDto {
  journeys?: JourneyDto[];
  startDate?: string;
  endDate?: string;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type JourneyDtoId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type JourneyDtoTotalMiles = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type JourneyDtoHomeLocationId = number | string;

export interface JourneyDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: JourneyDtoId;
  date?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalMiles?: JourneyDtoTotalMiles;
  isManualMiles?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  homeLocationId?: JourneyDtoHomeLocationId;
  trips?: JourneyTripDto[];
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type JourneyTripDtoId = number | string;

export interface JourneyTripDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: JourneyTripDtoId;
  locationName?: string;
  reasonName?: string;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type LocationId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type LocationLatitude = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type LocationLongitude = number | string;

export interface Location {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: LocationId;
  name?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  latitude?: LocationLatitude;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  longitude?: LocationLongitude;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type LocationDtoId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type LocationDtoLatitude = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type LocationDtoLongitude = number | string;

export interface LocationDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: LocationDtoId;
  name?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  latitude?: LocationDtoLatitude;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  longitude?: LocationDtoLongitude;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type ReasonId = number | string;

export interface Reason {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: ReasonId;
  name?: string;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type ReasonDtoId = number | string;

export interface ReasonDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: ReasonDtoId;
  name?: string;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type TripId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type TripLocationId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type TripReasonId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type TripJourneyId = number | string;

export interface Trip {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: TripId;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  locationId?: TripLocationId;
  location?: Location;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  reasonId?: TripReasonId;
  reason?: Reason;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  journeyId?: TripJourneyId;
  journey?: Journey;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type TripDtoId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type TripDtoLocationId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type TripDtoReasonId = number | string;

export interface TripDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: TripDtoId;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  locationId?: TripDtoLocationId;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  reasonId?: TripDtoReasonId;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type UpdateJourneyDtoId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type UpdateJourneyDtoTotalMiles = null | number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type UpdateJourneyDtoHomeLocationId = number | string;

export interface UpdateJourneyDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: UpdateJourneyDtoId;
  date: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalMiles?: UpdateJourneyDtoTotalMiles;
  isManualMiles: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  homeLocationId: UpdateJourneyDtoHomeLocationId;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type UpdateLocationDtoId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type UpdateLocationDtoLatitude = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type UpdateLocationDtoLongitude = number | string;

export interface UpdateLocationDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: UpdateLocationDtoId;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  latitude: UpdateLocationDtoLatitude;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  longitude: UpdateLocationDtoLongitude;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type UpdateReasonDtoId = number | string;

export interface UpdateReasonDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: UpdateReasonDtoId;
  /**
   * @minLength 2
   * @maxLength 50
   */
  name: string;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type UpdateTripDtoId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type UpdateTripDtoLocationId = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type UpdateTripDtoReasonId = number | string;

export interface UpdateTripDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: UpdateTripDtoId;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  locationId?: UpdateTripDtoLocationId;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  reasonId?: UpdateTripDtoReasonId;
}

export type GetApiJourneysParams = {
weekStart: string;
};

export const getGetApiJourneysUrl = (params: GetApiJourneysParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Journeys?${stringifiedParams}` : `/api/Journeys`
}

export const getApiJourneys = async (params: GetApiJourneysParams, options?: RequestInit): Promise<JourneyByWeekDto> => {
  
  const res = await fetch(getGetApiJourneysUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: JourneyByWeekDto = body ? JSON.parse(body) : {}
  return data
}





export const getGetApiJourneysQueryKey = (params?: GetApiJourneysParams,) => {
    return [
    `/api/Journeys`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiJourneysQueryOptions = <TData = Awaited<ReturnType<typeof getApiJourneys>>, TError = unknown>(params: GetApiJourneysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneys>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiJourneysQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiJourneys>>> = ({ signal }) => getApiJourneys(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiJourneys>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiJourneysQueryResult = NonNullable<Awaited<ReturnType<typeof getApiJourneys>>>
export type GetApiJourneysQueryError = unknown


export function useGetApiJourneys<TData = Awaited<ReturnType<typeof getApiJourneys>>, TError = unknown>(
 params: GetApiJourneysParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneys>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiJourneys>>,
          TError,
          Awaited<ReturnType<typeof getApiJourneys>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiJourneys<TData = Awaited<ReturnType<typeof getApiJourneys>>, TError = unknown>(
 params: GetApiJourneysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneys>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiJourneys>>,
          TError,
          Awaited<ReturnType<typeof getApiJourneys>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiJourneys<TData = Awaited<ReturnType<typeof getApiJourneys>>, TError = unknown>(
 params: GetApiJourneysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneys>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiJourneys<TData = Awaited<ReturnType<typeof getApiJourneys>>, TError = unknown>(
 params: GetApiJourneysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneys>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiJourneysQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPostApiJourneysUrl = () => {


  

  return `/api/Journeys`
}

export const postApiJourneys = async (createJourneyDto: CreateJourneyDto, options?: RequestInit): Promise<JourneyDto> => {
  
  const res = await fetch(getPostApiJourneysUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createJourneyDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: JourneyDto = body ? JSON.parse(body) : {}
  return data
}




export const getPostApiJourneysMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiJourneys>>, TError,{data: CreateJourneyDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiJourneys>>, TError,{data: CreateJourneyDto}, TContext> => {

const mutationKey = ['postApiJourneys'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiJourneys>>, {data: CreateJourneyDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiJourneys(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiJourneysMutationResult = NonNullable<Awaited<ReturnType<typeof postApiJourneys>>>
    export type PostApiJourneysMutationBody = CreateJourneyDto
    export type PostApiJourneysMutationError = unknown

    export const usePostApiJourneys = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiJourneys>>, TError,{data: CreateJourneyDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiJourneys>>,
        TError,
        {data: CreateJourneyDto},
        TContext
      > => {

      const mutationOptions = getPostApiJourneysMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getGetApiJourneysIdUrl = (id: number | string,) => {


  

  return `/api/Journeys/${id}`
}

export const getApiJourneysId = async (id: number | string, options?: RequestInit): Promise<JourneyDto> => {
  
  const res = await fetch(getGetApiJourneysIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: JourneyDto = body ? JSON.parse(body) : {}
  return data
}





export const getGetApiJourneysIdQueryKey = (id?: number | string,) => {
    return [
    `/api/Journeys/${id}`
    ] as const;
    }

    
export const getGetApiJourneysIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiJourneysId>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiJourneysIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiJourneysId>>> = ({ signal }) => getApiJourneysId(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiJourneysIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiJourneysId>>>
export type GetApiJourneysIdQueryError = unknown


export function useGetApiJourneysId<TData = Awaited<ReturnType<typeof getApiJourneysId>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiJourneysId>>,
          TError,
          Awaited<ReturnType<typeof getApiJourneysId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiJourneysId<TData = Awaited<ReturnType<typeof getApiJourneysId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiJourneysId>>,
          TError,
          Awaited<ReturnType<typeof getApiJourneysId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiJourneysId<TData = Awaited<ReturnType<typeof getApiJourneysId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiJourneysId<TData = Awaited<ReturnType<typeof getApiJourneysId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiJourneysIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPutApiJourneysIdUrl = (id: number | string,) => {


  

  return `/api/Journeys/${id}`
}

export const putApiJourneysId = async (id: number | string,
    updateJourneyDto: UpdateJourneyDto, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getPutApiJourneysIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateJourneyDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}




export const getPutApiJourneysIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiJourneysId>>, TError,{id: number | string;data: UpdateJourneyDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiJourneysId>>, TError,{id: number | string;data: UpdateJourneyDto}, TContext> => {

const mutationKey = ['putApiJourneysId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiJourneysId>>, {id: number | string;data: UpdateJourneyDto}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiJourneysId(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiJourneysIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiJourneysId>>>
    export type PutApiJourneysIdMutationBody = UpdateJourneyDto
    export type PutApiJourneysIdMutationError = unknown

    export const usePutApiJourneysId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiJourneysId>>, TError,{id: number | string;data: UpdateJourneyDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiJourneysId>>,
        TError,
        {id: number | string;data: UpdateJourneyDto},
        TContext
      > => {

      const mutationOptions = getPutApiJourneysIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getDeleteApiJourneysIdUrl = (id: number | string,) => {


  

  return `/api/Journeys/${id}`
}

export const deleteApiJourneysId = async (id: number | string, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getDeleteApiJourneysIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}




export const getDeleteApiJourneysIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiJourneysId>>, TError,{id: number | string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiJourneysId>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['deleteApiJourneysId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiJourneysId>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiJourneysId(id,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiJourneysIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiJourneysId>>>
    
    export type DeleteApiJourneysIdMutationError = unknown

    export const useDeleteApiJourneysId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiJourneysId>>, TError,{id: number | string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiJourneysId>>,
        TError,
        {id: number | string},
        TContext
      > => {

      const mutationOptions = getDeleteApiJourneysIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getGetApiLocationsUrl = () => {


  

  return `/api/Locations`
}

export const getApiLocations = async ( options?: RequestInit): Promise<LocationDto[]> => {
  
  const res = await fetch(getGetApiLocationsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: LocationDto[] = body ? JSON.parse(body) : {}
  return data
}





export const getGetApiLocationsQueryKey = () => {
    return [
    `/api/Locations`
    ] as const;
    }

    
export const getGetApiLocationsQueryOptions = <TData = Awaited<ReturnType<typeof getApiLocations>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLocations>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLocationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLocations>>> = ({ signal }) => getApiLocations({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLocations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLocationsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLocations>>>
export type GetApiLocationsQueryError = unknown


export function useGetApiLocations<TData = Awaited<ReturnType<typeof getApiLocations>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLocations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLocations>>,
          TError,
          Awaited<ReturnType<typeof getApiLocations>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLocations<TData = Awaited<ReturnType<typeof getApiLocations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLocations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLocations>>,
          TError,
          Awaited<ReturnType<typeof getApiLocations>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLocations<TData = Awaited<ReturnType<typeof getApiLocations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLocations>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiLocations<TData = Awaited<ReturnType<typeof getApiLocations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLocations>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLocationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPostApiLocationsUrl = () => {


  

  return `/api/Locations`
}

export const postApiLocations = async (createLocationDto: CreateLocationDto, options?: RequestInit): Promise<LocationDto> => {
  
  const res = await fetch(getPostApiLocationsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createLocationDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: LocationDto = body ? JSON.parse(body) : {}
  return data
}




export const getPostApiLocationsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLocations>>, TError,{data: CreateLocationDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiLocations>>, TError,{data: CreateLocationDto}, TContext> => {

const mutationKey = ['postApiLocations'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLocations>>, {data: CreateLocationDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiLocations(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiLocationsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLocations>>>
    export type PostApiLocationsMutationBody = CreateLocationDto
    export type PostApiLocationsMutationError = unknown

    export const usePostApiLocations = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLocations>>, TError,{data: CreateLocationDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLocations>>,
        TError,
        {data: CreateLocationDto},
        TContext
      > => {

      const mutationOptions = getPostApiLocationsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getGetApiLocationsIdUrl = (id: number | string,) => {


  

  return `/api/Locations/${id}`
}

export const getApiLocationsId = async (id: number | string, options?: RequestInit): Promise<LocationDto> => {
  
  const res = await fetch(getGetApiLocationsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: LocationDto = body ? JSON.parse(body) : {}
  return data
}





export const getGetApiLocationsIdQueryKey = (id?: number | string,) => {
    return [
    `/api/Locations/${id}`
    ] as const;
    }

    
export const getGetApiLocationsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiLocationsId>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLocationsId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLocationsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLocationsId>>> = ({ signal }) => getApiLocationsId(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLocationsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLocationsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLocationsId>>>
export type GetApiLocationsIdQueryError = unknown


export function useGetApiLocationsId<TData = Awaited<ReturnType<typeof getApiLocationsId>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLocationsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLocationsId>>,
          TError,
          Awaited<ReturnType<typeof getApiLocationsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLocationsId<TData = Awaited<ReturnType<typeof getApiLocationsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLocationsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLocationsId>>,
          TError,
          Awaited<ReturnType<typeof getApiLocationsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLocationsId<TData = Awaited<ReturnType<typeof getApiLocationsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLocationsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiLocationsId<TData = Awaited<ReturnType<typeof getApiLocationsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLocationsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLocationsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPutApiLocationsIdUrl = (id: number | string,) => {


  

  return `/api/Locations/${id}`
}

export const putApiLocationsId = async (id: number | string,
    updateLocationDto: UpdateLocationDto, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getPutApiLocationsIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateLocationDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}




export const getPutApiLocationsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiLocationsId>>, TError,{id: number | string;data: UpdateLocationDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiLocationsId>>, TError,{id: number | string;data: UpdateLocationDto}, TContext> => {

const mutationKey = ['putApiLocationsId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiLocationsId>>, {id: number | string;data: UpdateLocationDto}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiLocationsId(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiLocationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiLocationsId>>>
    export type PutApiLocationsIdMutationBody = UpdateLocationDto
    export type PutApiLocationsIdMutationError = unknown

    export const usePutApiLocationsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiLocationsId>>, TError,{id: number | string;data: UpdateLocationDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiLocationsId>>,
        TError,
        {id: number | string;data: UpdateLocationDto},
        TContext
      > => {

      const mutationOptions = getPutApiLocationsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getDeleteApiLocationsIdUrl = (id: number | string,) => {


  

  return `/api/Locations/${id}`
}

export const deleteApiLocationsId = async (id: number | string, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getDeleteApiLocationsIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}




export const getDeleteApiLocationsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiLocationsId>>, TError,{id: number | string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiLocationsId>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['deleteApiLocationsId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiLocationsId>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiLocationsId(id,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiLocationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiLocationsId>>>
    
    export type DeleteApiLocationsIdMutationError = unknown

    export const useDeleteApiLocationsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiLocationsId>>, TError,{id: number | string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiLocationsId>>,
        TError,
        {id: number | string},
        TContext
      > => {

      const mutationOptions = getDeleteApiLocationsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getGetApiReasonsUrl = () => {


  

  return `/api/Reasons`
}

export const getApiReasons = async ( options?: RequestInit): Promise<ReasonDto[]> => {
  
  const res = await fetch(getGetApiReasonsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ReasonDto[] = body ? JSON.parse(body) : {}
  return data
}





export const getGetApiReasonsQueryKey = () => {
    return [
    `/api/Reasons`
    ] as const;
    }

    
export const getGetApiReasonsQueryOptions = <TData = Awaited<ReturnType<typeof getApiReasons>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReasons>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiReasonsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiReasons>>> = ({ signal }) => getApiReasons({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiReasons>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiReasonsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiReasons>>>
export type GetApiReasonsQueryError = unknown


export function useGetApiReasons<TData = Awaited<ReturnType<typeof getApiReasons>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReasons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReasons>>,
          TError,
          Awaited<ReturnType<typeof getApiReasons>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReasons<TData = Awaited<ReturnType<typeof getApiReasons>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReasons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReasons>>,
          TError,
          Awaited<ReturnType<typeof getApiReasons>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReasons<TData = Awaited<ReturnType<typeof getApiReasons>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReasons>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiReasons<TData = Awaited<ReturnType<typeof getApiReasons>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReasons>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiReasonsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPostApiReasonsUrl = () => {


  

  return `/api/Reasons`
}

export const postApiReasons = async (createReasonDto: CreateReasonDto, options?: RequestInit): Promise<ReasonDto> => {
  
  const res = await fetch(getPostApiReasonsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createReasonDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ReasonDto = body ? JSON.parse(body) : {}
  return data
}




export const getPostApiReasonsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiReasons>>, TError,{data: CreateReasonDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiReasons>>, TError,{data: CreateReasonDto}, TContext> => {

const mutationKey = ['postApiReasons'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiReasons>>, {data: CreateReasonDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiReasons(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiReasonsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiReasons>>>
    export type PostApiReasonsMutationBody = CreateReasonDto
    export type PostApiReasonsMutationError = unknown

    export const usePostApiReasons = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiReasons>>, TError,{data: CreateReasonDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiReasons>>,
        TError,
        {data: CreateReasonDto},
        TContext
      > => {

      const mutationOptions = getPostApiReasonsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getGetApiReasonsIdUrl = (id: number | string,) => {


  

  return `/api/Reasons/${id}`
}

export const getApiReasonsId = async (id: number | string, options?: RequestInit): Promise<ReasonDto> => {
  
  const res = await fetch(getGetApiReasonsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ReasonDto = body ? JSON.parse(body) : {}
  return data
}





export const getGetApiReasonsIdQueryKey = (id?: number | string,) => {
    return [
    `/api/Reasons/${id}`
    ] as const;
    }

    
export const getGetApiReasonsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiReasonsId>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReasonsId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiReasonsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiReasonsId>>> = ({ signal }) => getApiReasonsId(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiReasonsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiReasonsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiReasonsId>>>
export type GetApiReasonsIdQueryError = unknown


export function useGetApiReasonsId<TData = Awaited<ReturnType<typeof getApiReasonsId>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReasonsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReasonsId>>,
          TError,
          Awaited<ReturnType<typeof getApiReasonsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReasonsId<TData = Awaited<ReturnType<typeof getApiReasonsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReasonsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReasonsId>>,
          TError,
          Awaited<ReturnType<typeof getApiReasonsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReasonsId<TData = Awaited<ReturnType<typeof getApiReasonsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReasonsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiReasonsId<TData = Awaited<ReturnType<typeof getApiReasonsId>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReasonsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiReasonsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPutApiReasonsIdUrl = (id: number | string,) => {


  

  return `/api/Reasons/${id}`
}

export const putApiReasonsId = async (id: number | string,
    updateReasonDto: UpdateReasonDto, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getPutApiReasonsIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateReasonDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}




export const getPutApiReasonsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiReasonsId>>, TError,{id: number | string;data: UpdateReasonDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiReasonsId>>, TError,{id: number | string;data: UpdateReasonDto}, TContext> => {

const mutationKey = ['putApiReasonsId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiReasonsId>>, {id: number | string;data: UpdateReasonDto}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiReasonsId(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiReasonsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiReasonsId>>>
    export type PutApiReasonsIdMutationBody = UpdateReasonDto
    export type PutApiReasonsIdMutationError = unknown

    export const usePutApiReasonsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiReasonsId>>, TError,{id: number | string;data: UpdateReasonDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiReasonsId>>,
        TError,
        {id: number | string;data: UpdateReasonDto},
        TContext
      > => {

      const mutationOptions = getPutApiReasonsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getDeleteApiReasonsIdUrl = (id: number | string,) => {


  

  return `/api/Reasons/${id}`
}

export const deleteApiReasonsId = async (id: number | string, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getDeleteApiReasonsIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}




export const getDeleteApiReasonsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiReasonsId>>, TError,{id: number | string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiReasonsId>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['deleteApiReasonsId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiReasonsId>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiReasonsId(id,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiReasonsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiReasonsId>>>
    
    export type DeleteApiReasonsIdMutationError = unknown

    export const useDeleteApiReasonsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiReasonsId>>, TError,{id: number | string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiReasonsId>>,
        TError,
        {id: number | string},
        TContext
      > => {

      const mutationOptions = getDeleteApiReasonsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getGetApiJourneysJourneyIdTripsUrl = (journeyId: number | string,) => {


  

  return `/api/journeys/${journeyId}/Trips`
}

export const getApiJourneysJourneyIdTrips = async (journeyId: number | string, options?: RequestInit): Promise<TripDto[]> => {
  
  const res = await fetch(getGetApiJourneysJourneyIdTripsUrl(journeyId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: TripDto[] = body ? JSON.parse(body) : {}
  return data
}





export const getGetApiJourneysJourneyIdTripsQueryKey = (journeyId?: number | string,) => {
    return [
    `/api/journeys/${journeyId}/Trips`
    ] as const;
    }

    
export const getGetApiJourneysJourneyIdTripsQueryOptions = <TData = Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>, TError = unknown>(journeyId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiJourneysJourneyIdTripsQueryKey(journeyId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>> = ({ signal }) => getApiJourneysJourneyIdTrips(journeyId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(journeyId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiJourneysJourneyIdTripsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>>
export type GetApiJourneysJourneyIdTripsQueryError = unknown


export function useGetApiJourneysJourneyIdTrips<TData = Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>, TError = unknown>(
 journeyId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>,
          TError,
          Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiJourneysJourneyIdTrips<TData = Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>, TError = unknown>(
 journeyId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>,
          TError,
          Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiJourneysJourneyIdTrips<TData = Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>, TError = unknown>(
 journeyId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiJourneysJourneyIdTrips<TData = Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>, TError = unknown>(
 journeyId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTrips>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiJourneysJourneyIdTripsQueryOptions(journeyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPostApiJourneysJourneyIdTripsUrl = (journeyId: number | string,) => {


  

  return `/api/journeys/${journeyId}/Trips`
}

export const postApiJourneysJourneyIdTrips = async (journeyId: number | string,
    createTripDto: CreateTripDto, options?: RequestInit): Promise<Trip> => {
  
  const res = await fetch(getPostApiJourneysJourneyIdTripsUrl(journeyId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTripDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: Trip = body ? JSON.parse(body) : {}
  return data
}




export const getPostApiJourneysJourneyIdTripsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiJourneysJourneyIdTrips>>, TError,{journeyId: number | string;data: CreateTripDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiJourneysJourneyIdTrips>>, TError,{journeyId: number | string;data: CreateTripDto}, TContext> => {

const mutationKey = ['postApiJourneysJourneyIdTrips'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiJourneysJourneyIdTrips>>, {journeyId: number | string;data: CreateTripDto}> = (props) => {
          const {journeyId,data} = props ?? {};

          return  postApiJourneysJourneyIdTrips(journeyId,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiJourneysJourneyIdTripsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiJourneysJourneyIdTrips>>>
    export type PostApiJourneysJourneyIdTripsMutationBody = CreateTripDto
    export type PostApiJourneysJourneyIdTripsMutationError = unknown

    export const usePostApiJourneysJourneyIdTrips = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiJourneysJourneyIdTrips>>, TError,{journeyId: number | string;data: CreateTripDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiJourneysJourneyIdTrips>>,
        TError,
        {journeyId: number | string;data: CreateTripDto},
        TContext
      > => {

      const mutationOptions = getPostApiJourneysJourneyIdTripsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getGetApiJourneysJourneyIdTripsTripIdUrl = (journeyId: number | string,
    tripId: number | string,) => {


  

  return `/api/journeys/${journeyId}/Trips/${tripId}`
}

export const getApiJourneysJourneyIdTripsTripId = async (journeyId: number | string,
    tripId: number | string, options?: RequestInit): Promise<Trip> => {
  
  const res = await fetch(getGetApiJourneysJourneyIdTripsTripIdUrl(journeyId,tripId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: Trip = body ? JSON.parse(body) : {}
  return data
}





export const getGetApiJourneysJourneyIdTripsTripIdQueryKey = (journeyId?: number | string,
    tripId?: number | string,) => {
    return [
    `/api/journeys/${journeyId}/Trips/${tripId}`
    ] as const;
    }

    
export const getGetApiJourneysJourneyIdTripsTripIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>, TError = unknown>(journeyId: number | string,
    tripId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiJourneysJourneyIdTripsTripIdQueryKey(journeyId,tripId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>> = ({ signal }) => getApiJourneysJourneyIdTripsTripId(journeyId,tripId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(journeyId && tripId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiJourneysJourneyIdTripsTripIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>>
export type GetApiJourneysJourneyIdTripsTripIdQueryError = unknown


export function useGetApiJourneysJourneyIdTripsTripId<TData = Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>, TError = unknown>(
 journeyId: number | string,
    tripId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>,
          TError,
          Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiJourneysJourneyIdTripsTripId<TData = Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>, TError = unknown>(
 journeyId: number | string,
    tripId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>,
          TError,
          Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiJourneysJourneyIdTripsTripId<TData = Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>, TError = unknown>(
 journeyId: number | string,
    tripId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiJourneysJourneyIdTripsTripId<TData = Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>, TError = unknown>(
 journeyId: number | string,
    tripId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJourneysJourneyIdTripsTripId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiJourneysJourneyIdTripsTripIdQueryOptions(journeyId,tripId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPutApiJourneysJourneyIdTripsTripIdUrl = (journeyId: number | string,
    tripId: number | string,) => {


  

  return `/api/journeys/${journeyId}/Trips/${tripId}`
}

export const putApiJourneysJourneyIdTripsTripId = async (journeyId: number | string,
    tripId: number | string,
    updateTripDto: UpdateTripDto, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getPutApiJourneysJourneyIdTripsTripIdUrl(journeyId,tripId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTripDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}




export const getPutApiJourneysJourneyIdTripsTripIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiJourneysJourneyIdTripsTripId>>, TError,{journeyId: number | string;tripId: number | string;data: UpdateTripDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiJourneysJourneyIdTripsTripId>>, TError,{journeyId: number | string;tripId: number | string;data: UpdateTripDto}, TContext> => {

const mutationKey = ['putApiJourneysJourneyIdTripsTripId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiJourneysJourneyIdTripsTripId>>, {journeyId: number | string;tripId: number | string;data: UpdateTripDto}> = (props) => {
          const {journeyId,tripId,data} = props ?? {};

          return  putApiJourneysJourneyIdTripsTripId(journeyId,tripId,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiJourneysJourneyIdTripsTripIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiJourneysJourneyIdTripsTripId>>>
    export type PutApiJourneysJourneyIdTripsTripIdMutationBody = UpdateTripDto
    export type PutApiJourneysJourneyIdTripsTripIdMutationError = unknown

    export const usePutApiJourneysJourneyIdTripsTripId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiJourneysJourneyIdTripsTripId>>, TError,{journeyId: number | string;tripId: number | string;data: UpdateTripDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiJourneysJourneyIdTripsTripId>>,
        TError,
        {journeyId: number | string;tripId: number | string;data: UpdateTripDto},
        TContext
      > => {

      const mutationOptions = getPutApiJourneysJourneyIdTripsTripIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getDeleteApiJourneysJourneyIdTripsTripIdUrl = (journeyId: number | string,
    tripId: number | string,) => {


  

  return `/api/journeys/${journeyId}/Trips/${tripId}`
}

export const deleteApiJourneysJourneyIdTripsTripId = async (journeyId: number | string,
    tripId: number | string, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getDeleteApiJourneysJourneyIdTripsTripIdUrl(journeyId,tripId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}




export const getDeleteApiJourneysJourneyIdTripsTripIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiJourneysJourneyIdTripsTripId>>, TError,{journeyId: number | string;tripId: number | string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiJourneysJourneyIdTripsTripId>>, TError,{journeyId: number | string;tripId: number | string}, TContext> => {

const mutationKey = ['deleteApiJourneysJourneyIdTripsTripId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiJourneysJourneyIdTripsTripId>>, {journeyId: number | string;tripId: number | string}> = (props) => {
          const {journeyId,tripId} = props ?? {};

          return  deleteApiJourneysJourneyIdTripsTripId(journeyId,tripId,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiJourneysJourneyIdTripsTripIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiJourneysJourneyIdTripsTripId>>>
    
    export type DeleteApiJourneysJourneyIdTripsTripIdMutationError = unknown

    export const useDeleteApiJourneysJourneyIdTripsTripId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiJourneysJourneyIdTripsTripId>>, TError,{journeyId: number | string;tripId: number | string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiJourneysJourneyIdTripsTripId>>,
        TError,
        {journeyId: number | string;tripId: number | string},
        TContext
      > => {

      const mutationOptions = getDeleteApiJourneysJourneyIdTripsTripIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
