/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailrecipientsIndexRouteImport } from './routes/emailrecipients/index'
import { Route as ReportsIndexRouteImport } from './routes/Reports/index'
import { Route as ReceiptsIndexRouteImport } from './routes/Receipts/index'
import { Route as ReasonsIndexRouteImport } from './routes/Reasons/index'
import { Route as PurchasesIndexRouteImport } from './routes/Purchases/index'
import { Route as ProfileIndexRouteImport } from './routes/Profile/index'
import { Route as PreferencesIndexRouteImport } from './routes/Preferences/index'
import { Route as LocationsIndexRouteImport } from './routes/Locations/index'
import { Route as JourneysIndexRouteImport } from './routes/Journeys/index'
import { Route as EmailrecipientsNewRouteImport } from './routes/emailrecipients/new'
import { Route as ReportsNewRouteImport } from './routes/Reports/new'
import { Route as ReceiptsOcrRouteImport } from './routes/Receipts/ocr'
import { Route as ReceiptsNewRouteImport } from './routes/Receipts/new'
import { Route as ReasonsNewRouteImport } from './routes/Reasons/new'
import { Route as PurchasesNewRouteImport } from './routes/Purchases/new'
import { Route as LocationsNewRouteImport } from './routes/Locations/new'
import { Route as ReportsReportIdIndexRouteImport } from './routes/Reports/$reportId/index'
import { Route as ReceiptsReceiptIdIndexRouteImport } from './routes/Receipts/$receiptId/index'
import { Route as PurchasesPurchaseIdIndexRouteImport } from './routes/Purchases/$purchaseId/index'
import { Route as LocationsLocationIdIndexRouteImport } from './routes/Locations/$locationId/index'
import { Route as PurchasesPurchaseIdEditRouteImport } from './routes/Purchases/$purchaseId/edit'
import { Route as JourneysJourneyIdEditRouteImport } from './routes/Journeys/$journeyId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailrecipientsIndexRoute = EmailrecipientsIndexRouteImport.update({
  id: '/emailrecipients/',
  path: '/emailrecipients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/Reports/',
  path: '/Reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/Receipts/',
  path: '/Receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReasonsIndexRoute = ReasonsIndexRouteImport.update({
  id: '/Reasons/',
  path: '/Reasons/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesIndexRoute = PurchasesIndexRouteImport.update({
  id: '/Purchases/',
  path: '/Purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/Profile/',
  path: '/Profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesIndexRoute = PreferencesIndexRouteImport.update({
  id: '/Preferences/',
  path: '/Preferences/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/Locations/',
  path: '/Locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysIndexRoute = JourneysIndexRouteImport.update({
  id: '/Journeys/',
  path: '/Journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailrecipientsNewRoute = EmailrecipientsNewRouteImport.update({
  id: '/emailrecipients/new',
  path: '/emailrecipients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsNewRoute = ReportsNewRouteImport.update({
  id: '/Reports/new',
  path: '/Reports/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsOcrRoute = ReceiptsOcrRouteImport.update({
  id: '/Receipts/ocr',
  path: '/Receipts/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsNewRoute = ReceiptsNewRouteImport.update({
  id: '/Receipts/new',
  path: '/Receipts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReasonsNewRoute = ReasonsNewRouteImport.update({
  id: '/Reasons/new',
  path: '/Reasons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/Purchases/new',
  path: '/Purchases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsNewRoute = LocationsNewRouteImport.update({
  id: '/Locations/new',
  path: '/Locations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdIndexRoute = ReportsReportIdIndexRouteImport.update({
  id: '/Reports/$reportId/',
  path: '/Reports/$reportId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsReceiptIdIndexRoute = ReceiptsReceiptIdIndexRouteImport.update({
  id: '/Receipts/$receiptId/',
  path: '/Receipts/$receiptId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesPurchaseIdIndexRoute =
  PurchasesPurchaseIdIndexRouteImport.update({
    id: '/Purchases/$purchaseId/',
    path: '/Purchases/$purchaseId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsLocationIdIndexRoute =
  LocationsLocationIdIndexRouteImport.update({
    id: '/Locations/$locationId/',
    path: '/Locations/$locationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PurchasesPurchaseIdEditRoute = PurchasesPurchaseIdEditRouteImport.update({
  id: '/Purchases/$purchaseId/edit',
  path: '/Purchases/$purchaseId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysJourneyIdEditRoute = JourneysJourneyIdEditRouteImport.update({
  id: '/Journeys/$journeyId/edit',
  path: '/Journeys/$journeyId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Locations/new': typeof LocationsNewRoute
  '/Purchases/new': typeof PurchasesNewRoute
  '/Reasons/new': typeof ReasonsNewRoute
  '/Receipts/new': typeof ReceiptsNewRoute
  '/Receipts/ocr': typeof ReceiptsOcrRoute
  '/Reports/new': typeof ReportsNewRoute
  '/emailrecipients/new': typeof EmailrecipientsNewRoute
  '/Journeys': typeof JourneysIndexRoute
  '/Locations': typeof LocationsIndexRoute
  '/Preferences': typeof PreferencesIndexRoute
  '/Profile': typeof ProfileIndexRoute
  '/Purchases': typeof PurchasesIndexRoute
  '/Reasons': typeof ReasonsIndexRoute
  '/Receipts': typeof ReceiptsIndexRoute
  '/Reports': typeof ReportsIndexRoute
  '/emailrecipients': typeof EmailrecipientsIndexRoute
  '/Journeys/$journeyId/edit': typeof JourneysJourneyIdEditRoute
  '/Purchases/$purchaseId/edit': typeof PurchasesPurchaseIdEditRoute
  '/Locations/$locationId': typeof LocationsLocationIdIndexRoute
  '/Purchases/$purchaseId': typeof PurchasesPurchaseIdIndexRoute
  '/Receipts/$receiptId': typeof ReceiptsReceiptIdIndexRoute
  '/Reports/$reportId': typeof ReportsReportIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Locations/new': typeof LocationsNewRoute
  '/Purchases/new': typeof PurchasesNewRoute
  '/Reasons/new': typeof ReasonsNewRoute
  '/Receipts/new': typeof ReceiptsNewRoute
  '/Receipts/ocr': typeof ReceiptsOcrRoute
  '/Reports/new': typeof ReportsNewRoute
  '/emailrecipients/new': typeof EmailrecipientsNewRoute
  '/Journeys': typeof JourneysIndexRoute
  '/Locations': typeof LocationsIndexRoute
  '/Preferences': typeof PreferencesIndexRoute
  '/Profile': typeof ProfileIndexRoute
  '/Purchases': typeof PurchasesIndexRoute
  '/Reasons': typeof ReasonsIndexRoute
  '/Receipts': typeof ReceiptsIndexRoute
  '/Reports': typeof ReportsIndexRoute
  '/emailrecipients': typeof EmailrecipientsIndexRoute
  '/Journeys/$journeyId/edit': typeof JourneysJourneyIdEditRoute
  '/Purchases/$purchaseId/edit': typeof PurchasesPurchaseIdEditRoute
  '/Locations/$locationId': typeof LocationsLocationIdIndexRoute
  '/Purchases/$purchaseId': typeof PurchasesPurchaseIdIndexRoute
  '/Receipts/$receiptId': typeof ReceiptsReceiptIdIndexRoute
  '/Reports/$reportId': typeof ReportsReportIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Locations/new': typeof LocationsNewRoute
  '/Purchases/new': typeof PurchasesNewRoute
  '/Reasons/new': typeof ReasonsNewRoute
  '/Receipts/new': typeof ReceiptsNewRoute
  '/Receipts/ocr': typeof ReceiptsOcrRoute
  '/Reports/new': typeof ReportsNewRoute
  '/emailrecipients/new': typeof EmailrecipientsNewRoute
  '/Journeys/': typeof JourneysIndexRoute
  '/Locations/': typeof LocationsIndexRoute
  '/Preferences/': typeof PreferencesIndexRoute
  '/Profile/': typeof ProfileIndexRoute
  '/Purchases/': typeof PurchasesIndexRoute
  '/Reasons/': typeof ReasonsIndexRoute
  '/Receipts/': typeof ReceiptsIndexRoute
  '/Reports/': typeof ReportsIndexRoute
  '/emailrecipients/': typeof EmailrecipientsIndexRoute
  '/Journeys/$journeyId/edit': typeof JourneysJourneyIdEditRoute
  '/Purchases/$purchaseId/edit': typeof PurchasesPurchaseIdEditRoute
  '/Locations/$locationId/': typeof LocationsLocationIdIndexRoute
  '/Purchases/$purchaseId/': typeof PurchasesPurchaseIdIndexRoute
  '/Receipts/$receiptId/': typeof ReceiptsReceiptIdIndexRoute
  '/Reports/$reportId/': typeof ReportsReportIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Locations/new'
    | '/Purchases/new'
    | '/Reasons/new'
    | '/Receipts/new'
    | '/Receipts/ocr'
    | '/Reports/new'
    | '/emailrecipients/new'
    | '/Journeys'
    | '/Locations'
    | '/Preferences'
    | '/Profile'
    | '/Purchases'
    | '/Reasons'
    | '/Receipts'
    | '/Reports'
    | '/emailrecipients'
    | '/Journeys/$journeyId/edit'
    | '/Purchases/$purchaseId/edit'
    | '/Locations/$locationId'
    | '/Purchases/$purchaseId'
    | '/Receipts/$receiptId'
    | '/Reports/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Locations/new'
    | '/Purchases/new'
    | '/Reasons/new'
    | '/Receipts/new'
    | '/Receipts/ocr'
    | '/Reports/new'
    | '/emailrecipients/new'
    | '/Journeys'
    | '/Locations'
    | '/Preferences'
    | '/Profile'
    | '/Purchases'
    | '/Reasons'
    | '/Receipts'
    | '/Reports'
    | '/emailrecipients'
    | '/Journeys/$journeyId/edit'
    | '/Purchases/$purchaseId/edit'
    | '/Locations/$locationId'
    | '/Purchases/$purchaseId'
    | '/Receipts/$receiptId'
    | '/Reports/$reportId'
  id:
    | '__root__'
    | '/'
    | '/Locations/new'
    | '/Purchases/new'
    | '/Reasons/new'
    | '/Receipts/new'
    | '/Receipts/ocr'
    | '/Reports/new'
    | '/emailrecipients/new'
    | '/Journeys/'
    | '/Locations/'
    | '/Preferences/'
    | '/Profile/'
    | '/Purchases/'
    | '/Reasons/'
    | '/Receipts/'
    | '/Reports/'
    | '/emailrecipients/'
    | '/Journeys/$journeyId/edit'
    | '/Purchases/$purchaseId/edit'
    | '/Locations/$locationId/'
    | '/Purchases/$purchaseId/'
    | '/Receipts/$receiptId/'
    | '/Reports/$reportId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationsNewRoute: typeof LocationsNewRoute
  PurchasesNewRoute: typeof PurchasesNewRoute
  ReasonsNewRoute: typeof ReasonsNewRoute
  ReceiptsNewRoute: typeof ReceiptsNewRoute
  ReceiptsOcrRoute: typeof ReceiptsOcrRoute
  ReportsNewRoute: typeof ReportsNewRoute
  EmailrecipientsNewRoute: typeof EmailrecipientsNewRoute
  JourneysIndexRoute: typeof JourneysIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  PreferencesIndexRoute: typeof PreferencesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  PurchasesIndexRoute: typeof PurchasesIndexRoute
  ReasonsIndexRoute: typeof ReasonsIndexRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  EmailrecipientsIndexRoute: typeof EmailrecipientsIndexRoute
  JourneysJourneyIdEditRoute: typeof JourneysJourneyIdEditRoute
  PurchasesPurchaseIdEditRoute: typeof PurchasesPurchaseIdEditRoute
  LocationsLocationIdIndexRoute: typeof LocationsLocationIdIndexRoute
  PurchasesPurchaseIdIndexRoute: typeof PurchasesPurchaseIdIndexRoute
  ReceiptsReceiptIdIndexRoute: typeof ReceiptsReceiptIdIndexRoute
  ReportsReportIdIndexRoute: typeof ReportsReportIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emailrecipients/': {
      id: '/emailrecipients/'
      path: '/emailrecipients'
      fullPath: '/emailrecipients'
      preLoaderRoute: typeof EmailrecipientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Reports/': {
      id: '/Reports/'
      path: '/Reports'
      fullPath: '/Reports'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Receipts/': {
      id: '/Receipts/'
      path: '/Receipts'
      fullPath: '/Receipts'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Reasons/': {
      id: '/Reasons/'
      path: '/Reasons'
      fullPath: '/Reasons'
      preLoaderRoute: typeof ReasonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Purchases/': {
      id: '/Purchases/'
      path: '/Purchases'
      fullPath: '/Purchases'
      preLoaderRoute: typeof PurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Profile/': {
      id: '/Profile/'
      path: '/Profile'
      fullPath: '/Profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Preferences/': {
      id: '/Preferences/'
      path: '/Preferences'
      fullPath: '/Preferences'
      preLoaderRoute: typeof PreferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Locations/': {
      id: '/Locations/'
      path: '/Locations'
      fullPath: '/Locations'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Journeys/': {
      id: '/Journeys/'
      path: '/Journeys'
      fullPath: '/Journeys'
      preLoaderRoute: typeof JourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emailrecipients/new': {
      id: '/emailrecipients/new'
      path: '/emailrecipients/new'
      fullPath: '/emailrecipients/new'
      preLoaderRoute: typeof EmailrecipientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Reports/new': {
      id: '/Reports/new'
      path: '/Reports/new'
      fullPath: '/Reports/new'
      preLoaderRoute: typeof ReportsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Receipts/ocr': {
      id: '/Receipts/ocr'
      path: '/Receipts/ocr'
      fullPath: '/Receipts/ocr'
      preLoaderRoute: typeof ReceiptsOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Receipts/new': {
      id: '/Receipts/new'
      path: '/Receipts/new'
      fullPath: '/Receipts/new'
      preLoaderRoute: typeof ReceiptsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Reasons/new': {
      id: '/Reasons/new'
      path: '/Reasons/new'
      fullPath: '/Reasons/new'
      preLoaderRoute: typeof ReasonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Purchases/new': {
      id: '/Purchases/new'
      path: '/Purchases/new'
      fullPath: '/Purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Locations/new': {
      id: '/Locations/new'
      path: '/Locations/new'
      fullPath: '/Locations/new'
      preLoaderRoute: typeof LocationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Reports/$reportId/': {
      id: '/Reports/$reportId/'
      path: '/Reports/$reportId'
      fullPath: '/Reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Receipts/$receiptId/': {
      id: '/Receipts/$receiptId/'
      path: '/Receipts/$receiptId'
      fullPath: '/Receipts/$receiptId'
      preLoaderRoute: typeof ReceiptsReceiptIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Purchases/$purchaseId/': {
      id: '/Purchases/$purchaseId/'
      path: '/Purchases/$purchaseId'
      fullPath: '/Purchases/$purchaseId'
      preLoaderRoute: typeof PurchasesPurchaseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Locations/$locationId/': {
      id: '/Locations/$locationId/'
      path: '/Locations/$locationId'
      fullPath: '/Locations/$locationId'
      preLoaderRoute: typeof LocationsLocationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Purchases/$purchaseId/edit': {
      id: '/Purchases/$purchaseId/edit'
      path: '/Purchases/$purchaseId/edit'
      fullPath: '/Purchases/$purchaseId/edit'
      preLoaderRoute: typeof PurchasesPurchaseIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Journeys/$journeyId/edit': {
      id: '/Journeys/$journeyId/edit'
      path: '/Journeys/$journeyId/edit'
      fullPath: '/Journeys/$journeyId/edit'
      preLoaderRoute: typeof JourneysJourneyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationsNewRoute: LocationsNewRoute,
  PurchasesNewRoute: PurchasesNewRoute,
  ReasonsNewRoute: ReasonsNewRoute,
  ReceiptsNewRoute: ReceiptsNewRoute,
  ReceiptsOcrRoute: ReceiptsOcrRoute,
  ReportsNewRoute: ReportsNewRoute,
  EmailrecipientsNewRoute: EmailrecipientsNewRoute,
  JourneysIndexRoute: JourneysIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  PreferencesIndexRoute: PreferencesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  PurchasesIndexRoute: PurchasesIndexRoute,
  ReasonsIndexRoute: ReasonsIndexRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  EmailrecipientsIndexRoute: EmailrecipientsIndexRoute,
  JourneysJourneyIdEditRoute: JourneysJourneyIdEditRoute,
  PurchasesPurchaseIdEditRoute: PurchasesPurchaseIdEditRoute,
  LocationsLocationIdIndexRoute: LocationsLocationIdIndexRoute,
  PurchasesPurchaseIdIndexRoute: PurchasesPurchaseIdIndexRoute,
  ReceiptsReceiptIdIndexRoute: ReceiptsReceiptIdIndexRoute,
  ReportsReportIdIndexRoute: ReportsReportIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
